export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  TENANT_ADMIN: 'tenant_admin',
  HR_MANAGER: 'hr_manager',
  PAYROLL_MANAGER: 'payroll_manager',
  MANAGER: 'manager',
  EMPLOYEE: 'employee',
  FINANCE: 'finance',
  SALES: 'sales',
} as const;

export const PERMISSIONS = {
  USERS_READ: 'users:read',
  USERS_CREATE: 'users:create',
  USERS_UPDATE: 'users:update',
  USERS_DELETE: 'users:delete',
  EMPLOYEES_READ: 'employees:read',
  EMPLOYEES_CREATE: 'employees:create',
  EMPLOYEES_UPDATE: 'employees:update',
  EMPLOYEES_DELETE: 'employees:delete',
  PAYROLL_READ: 'payroll:read',
  PAYROLL_PROCESS: 'payroll:process',
  PAYROLL_FINALIZE: 'payroll:finalize',
  ATTENDANCE_READ: 'attendance:read',
  ATTENDANCE_MANAGE: 'attendance:manage',
  LEAVE_READ: 'leave:read',
  LEAVE_APPROVE: 'leave:approve',
  PROJECTS_READ: 'projects:read',
  PROJECTS_MANAGE: 'projects:manage',
  SALES_READ: 'sales:read',
  SALES_MANAGE: 'sales:manage',
  REPORTS_READ: 'reports:read',
  AUDIT_READ: 'audit:read',
} as const;
