export const APP_CONFIG = {
  name: import.meta.env.VITE_APP_NAME ?? 'HR Shakya ERP',
  apiBaseUrl: import.meta.env.VITE_API_BASE_URL ?? '',
  apiPrefix: import.meta.env.VITE_API_PREFIX ?? '/api/v1',
  authUseHttpOnlyCookies: import.meta.env.VITE_AUTH_USE_HTTP_ONLY_COOKIES === 'true',
} as const;

export const STORAGE_KEYS = {
  ACCESS_TOKEN: 'hr_shakya_access_token',
  REFRESH_TOKEN: 'hr_shakya_refresh_token',
} as const;

export const ROUTES = {
  HOME: '/',
  ERROR: '/error',
  ORGANIZATION: '/organization',
  SETTINGS: '/organization/settings',
  organizationEntity: (entityKey: string) => `/organization/${entityKey}`,
  RBAC: '/rbac',
  RBAC_ROLES: '/rbac/roles',
  RBAC_MATRIX: '/rbac/matrix',
  RBAC_SIMULATOR: '/rbac/simulator',
  EMPLOYEES: '/employees',
  EMPLOYEE_CREATE: '/employees/new',
  employeeDetail: (id: string) => `/employees/${id}`,
  RECRUITMENT: '/recruitment',
  RECRUITMENT_CANDIDATES: '/recruitment/candidates',
  RECRUITMENT_CANDIDATE_CREATE: '/recruitment/candidates/new',
  RECRUITMENT_PIPELINE: '/recruitment/pipeline',
  RECRUITMENT_INTERVIEWS: '/recruitment/interviews',
  recruitmentCandidateDetail: (id: string) => `/recruitment/candidates/${id}`,
  PROJECTS: '/projects',
  PROJECTS_LIST: '/projects/list',
  PROJECTS_CREATE: '/projects/new',
  projectDetail: (id: string) => `/projects/${id}`,
  WORKSPACE: '/workspace',
  ENTERPRISE: '/enterprise',
  MANAGER: '/manager',
  WORKSPACE_PROFILE: '/workspace/profile',
  WORKSPACE_PROJECTS: '/workspace/projects',
  WORKSPACE_TASKS: '/workspace/tasks',
  WORKSPACE_DOCUMENTS: '/workspace/documents',
  WORKSPACE_NOTIFICATIONS: '/workspace/notifications',
  WORKSPACE_ANNOUNCEMENTS: '/workspace/announcements',
  WORKSPACE_CALENDAR: '/workspace/calendar',
  WORKSPACE_ACTIVITY: '/workspace/activity',
  WORKSPACE_SEARCH: '/workspace/search',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  resetPasswordWithToken: (token: string) => `/reset-password/${token}`,
  ONBOARDING: '/onboarding',
  onboardingWithToken: (token: string) => `/onboarding/${token}`,
  ACCOUNT_ACTIVATION: '/account-activation',
  accountActivationWithToken: (token: string) => `/account-activation/${token}`,
  SESSIONS: '/account/sessions',
  UNAUTHORIZED: '/401',
  FORBIDDEN: '/403',
  NOT_FOUND: '/404',
  SESSION_EXPIRED: '/session-expired',
  MAINTENANCE: '/maintenance',
  SERVER_ERROR: '/500',
  NETWORK_ERROR: '/network-error',
  OFFLINE: '/offline',
  MODULE_LOAD_FAILURE: '/module-error',
  DATA_LOAD_FAILURE: '/data-error',
  UNEXPECTED_ERROR: '/unexpected-error',
  LEAVE_EXIT: '/leave-exit',
  LEAVE_APPLY: '/leave-exit/apply',
  LEAVE_REQUESTS: '/leave-exit/requests',
  LEAVE_CALENDAR: '/leave-exit/calendar',
  LEAVE_BALANCES: '/leave-exit/balances',
  LEAVE_POLICIES: '/leave-exit/policies',
  RESIGNATION: '/leave-exit/resignation',
  EXIT: '/leave-exit/exit',
  APPROVAL_INBOX: '/approvals/inbox',
  APPROVAL_HISTORY: '/approvals/history',
  APPROVAL_WORKFLOWS: '/approvals/workflows',
  ORGANIZATION_SETUP: '/organization/setup',
  ORGANIZATION_CHART: '/organization/chart',
  organizationEntityDetail: (entityKey: string, id: string) => `/organization/${entityKey}/${id}`,
  RBAC_TEMPLATES: '/rbac/templates',
  ADMIN_TEMPLATES: '/admin/templates',
  FEATURE_FLAGS: '/system/feature-flags',
  SYSTEM_DASHBOARD: '/system/dashboard',
  ADMIN_SETTINGS: '/system/settings',
  CONFIGURATION: '/system/configuration',
  CONFIGURATION_SECTION: '/system/configuration',
  configurationSection: (section: string) => `/system/configuration/${section}`,
  NAVIGATION_MANAGER: '/system/navigation',
  AUDIT_EXPLORER: '/system/audit',
  SYSTEM_HEALTH: '/system/health',
  ATTENDANCE: '/attendance',
  ATTENDANCE_ADMIN: '/attendance/admin',
  ATTENDANCE_HR: '/attendance/hr',
  ATTENDANCE_TEAM: '/attendance/team',
  WORKSPACE_ATTENDANCE: '/workspace/attendance',
  ATTENDANCE_REPORTS: '/attendance/reports',
  PAYROLL: '/payroll',
  PAYROLL_ADMIN: '/payroll/admin',
  PAYROLL_FINANCE: '/payroll/finance',
  PAYROLL_HR: '/payroll/hr',
  WORKSPACE_PAYROLL: '/workspace/payroll',
  PAYROLL_REPORTS: '/payroll/reports',
  SALES: '/sales',
  SALES_ADMIN: '/sales/admin',
  SALES_MANAGER: '/sales/manager',
  SALES_EXECUTIVE: '/sales/my',
  SALES_REPORTS: '/sales/reports',
  salesLeadDetail: (id: string) => `/sales/leads/${id}`,
  COMMUNICATION: '/communication',
  COMMUNICATION_ADMIN: '/communication/admin',
  COMMUNICATION_MANAGER: '/communication/manager',
  COMMUNICATION_INBOX: '/communication/inbox',
  COMMUNICATION_REPORTS: '/communication/reports',
  COMMUNICATION_SEARCH: '/communication/search',
  WORKSPACE_MESSAGES: '/workspace/messages',
  REPORTS: '/reports',
  REPORTS_EXECUTIVE: '/reports/executive',
  REPORTS_DASHBOARD: '/reports/dashboard',
  reportsDashboardRole: (role: string) => `/reports/dashboard/${role}`,
  REPORTS_RUN: '/reports/run',
  reportRun: (domain: string, type: string) => `/reports/run/${domain}/${type}`,
  ANALYTICS: '/analytics',
  INTEGRATIONS: '/system/integrations',
  INTEGRATION_CONNECTORS: '/system/integrations/connectors',
  API_KEYS: '/system/api-keys',
  WEBHOOKS: '/system/webhooks',
  IMPORT_CENTER: '/system/import',
  EXPORT_CENTER: '/system/export',
  SCHEDULER: '/system/scheduler',
  INTEGRATION_LOGS: '/system/integration-logs',
  BACKUPS: '/system/backups',
} as const;
